/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MapRouteImport } from './routes/map'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInquiriesRouteImport } from './routes/_authenticated/inquiries'
import { Route as AuthenticatedJoinRouteImport } from './routes/_authenticated/join'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPendingRouteImport } from './routes/_authenticated/pending'
import { Route as BrokersIndexRouteImport } from './routes/brokers.index'
import { Route as BrokersSlugRouteImport } from './routes/brokers.$slug'
import { Route as DemoCentralPointRouteImport } from './routes/demo.central-point'
import { Route as IndustrialIndexRouteImport } from './routes/industrial.index'
import { Route as IndustrialIdRouteImport } from './routes/industrial.$id'
import { Route as MallsIndexRouteImport } from './routes/malls.index'
import { Route as MallsIdRouteImport } from './routes/malls.$id'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as ApiPublicNotificationsWhatsappDispatchRouteImport } from './routes/api/public/notifications/whatsapp-dispatch'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInquiriesRoute = AuthenticatedInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJoinRoute = AuthenticatedJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPendingRoute = AuthenticatedPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BrokersIndexRoute = BrokersIndexRouteImport.update({
  id: '/brokers/',
  path: '/brokers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokersSlugRoute = BrokersSlugRouteImport.update({
  id: '/brokers/$slug',
  path: '/brokers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCentralPointRoute = DemoCentralPointRouteImport.update({
  id: '/demo/central-point',
  path: '/demo/central-point',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrialIndexRoute = IndustrialIndexRouteImport.update({
  id: '/industrial/',
  path: '/industrial/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrialIdRoute = IndustrialIdRouteImport.update({
  id: '/industrial/$id',
  path: '/industrial/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MallsIndexRoute = MallsIndexRouteImport.update({
  id: '/malls/',
  path: '/malls/',
  getParentRoute: () => rootRouteImport,
} as any)
const MallsIdRoute = MallsIdRouteImport.update({
  id: '/malls/$id',
  path: '/malls/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotificationsWhatsappDispatchRoute =
  ApiPublicNotificationsWhatsappDispatchRouteImport.update({
    id: '/api/public/notifications/whatsapp-dispatch',
    path: '/api/public/notifications/whatsapp-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inquiries': typeof AuthenticatedInquiriesRoute
  '/join': typeof AuthenticatedJoinRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/brokers/$slug': typeof BrokersSlugRoute
  '/demo/central-point': typeof DemoCentralPointRoute
  '/industrial/$id': typeof IndustrialIdRoute
  '/malls/$id': typeof MallsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/brokers/': typeof BrokersIndexRoute
  '/industrial/': typeof IndustrialIndexRoute
  '/malls/': typeof MallsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/public/notifications/whatsapp-dispatch': typeof ApiPublicNotificationsWhatsappDispatchRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inquiries': typeof AuthenticatedInquiriesRoute
  '/join': typeof AuthenticatedJoinRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/pending': typeof AuthenticatedPendingRoute
  '/brokers/$slug': typeof BrokersSlugRoute
  '/demo/central-point': typeof DemoCentralPointRoute
  '/industrial/$id': typeof IndustrialIdRoute
  '/malls/$id': typeof MallsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/brokers': typeof BrokersIndexRoute
  '/industrial': typeof IndustrialIndexRoute
  '/malls': typeof MallsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/public/notifications/whatsapp-dispatch': typeof ApiPublicNotificationsWhatsappDispatchRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inquiries': typeof AuthenticatedInquiriesRoute
  '/_authenticated/join': typeof AuthenticatedJoinRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/pending': typeof AuthenticatedPendingRoute
  '/brokers/$slug': typeof BrokersSlugRoute
  '/demo/central-point': typeof DemoCentralPointRoute
  '/industrial/$id': typeof IndustrialIdRoute
  '/malls/$id': typeof MallsIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/brokers/': typeof BrokersIndexRoute
  '/industrial/': typeof IndustrialIndexRoute
  '/malls/': typeof MallsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/public/notifications/whatsapp-dispatch': typeof ApiPublicNotificationsWhatsappDispatchRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/map'
    | '/reset-password'
    | '/sell'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/inquiries'
    | '/join'
    | '/notifications'
    | '/pending'
    | '/brokers/$slug'
    | '/demo/central-point'
    | '/industrial/$id'
    | '/malls/$id'
    | '/projects/$id'
    | '/properties/$id'
    | '/brokers/'
    | '/industrial/'
    | '/malls/'
    | '/projects/'
    | '/api/public/notifications/whatsapp-dispatch'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/map'
    | '/reset-password'
    | '/sell'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/inquiries'
    | '/join'
    | '/notifications'
    | '/pending'
    | '/brokers/$slug'
    | '/demo/central-point'
    | '/industrial/$id'
    | '/malls/$id'
    | '/projects/$id'
    | '/properties/$id'
    | '/brokers'
    | '/industrial'
    | '/malls'
    | '/projects'
    | '/api/public/notifications/whatsapp-dispatch'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/map'
    | '/reset-password'
    | '/sell'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/inquiries'
    | '/_authenticated/join'
    | '/_authenticated/notifications'
    | '/_authenticated/pending'
    | '/brokers/$slug'
    | '/demo/central-point'
    | '/industrial/$id'
    | '/malls/$id'
    | '/projects/$id'
    | '/properties/$id'
    | '/brokers/'
    | '/industrial/'
    | '/malls/'
    | '/projects/'
    | '/api/public/notifications/whatsapp-dispatch'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MapRoute: typeof MapRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellRoute: typeof SellRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BrokersSlugRoute: typeof BrokersSlugRoute
  DemoCentralPointRoute: typeof DemoCentralPointRoute
  IndustrialIdRoute: typeof IndustrialIdRoute
  MallsIdRoute: typeof MallsIdRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  BrokersIndexRoute: typeof BrokersIndexRoute
  IndustrialIndexRoute: typeof IndustrialIndexRoute
  MallsIndexRoute: typeof MallsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiPublicNotificationsWhatsappDispatchRoute: typeof ApiPublicNotificationsWhatsappDispatchRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inquiries': {
      id: '/_authenticated/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof AuthenticatedInquiriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/join': {
      id: '/_authenticated/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthenticatedJoinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pending': {
      id: '/_authenticated/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof AuthenticatedPendingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/brokers/': {
      id: '/brokers/'
      path: '/brokers'
      fullPath: '/brokers/'
      preLoaderRoute: typeof BrokersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokers/$slug': {
      id: '/brokers/$slug'
      path: '/brokers/$slug'
      fullPath: '/brokers/$slug'
      preLoaderRoute: typeof BrokersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/central-point': {
      id: '/demo/central-point'
      path: '/demo/central-point'
      fullPath: '/demo/central-point'
      preLoaderRoute: typeof DemoCentralPointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industrial/': {
      id: '/industrial/'
      path: '/industrial'
      fullPath: '/industrial/'
      preLoaderRoute: typeof IndustrialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industrial/$id': {
      id: '/industrial/$id'
      path: '/industrial/$id'
      fullPath: '/industrial/$id'
      preLoaderRoute: typeof IndustrialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malls/': {
      id: '/malls/'
      path: '/malls'
      fullPath: '/malls/'
      preLoaderRoute: typeof MallsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malls/$id': {
      id: '/malls/$id'
      path: '/malls/$id'
      fullPath: '/malls/$id'
      preLoaderRoute: typeof MallsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notifications/whatsapp-dispatch': {
      id: '/api/public/notifications/whatsapp-dispatch'
      path: '/api/public/notifications/whatsapp-dispatch'
      fullPath: '/api/public/notifications/whatsapp-dispatch'
      preLoaderRoute: typeof ApiPublicNotificationsWhatsappDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInquiriesRoute: typeof AuthenticatedInquiriesRoute
  AuthenticatedJoinRoute: typeof AuthenticatedJoinRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPendingRoute: typeof AuthenticatedPendingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInquiriesRoute: AuthenticatedInquiriesRoute,
  AuthenticatedJoinRoute: AuthenticatedJoinRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPendingRoute: AuthenticatedPendingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MapRoute: MapRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SellRoute: SellRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BrokersSlugRoute: BrokersSlugRoute,
  DemoCentralPointRoute: DemoCentralPointRoute,
  IndustrialIdRoute: IndustrialIdRoute,
  MallsIdRoute: MallsIdRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  BrokersIndexRoute: BrokersIndexRoute,
  IndustrialIndexRoute: IndustrialIndexRoute,
  MallsIndexRoute: MallsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiPublicNotificationsWhatsappDispatchRoute:
    ApiPublicNotificationsWhatsappDispatchRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
